# These are supported funding model platforms

github: ['ShikariBaaZ', 'kennedy-ex', 'aryazakaria01', 'FeriEXP']
community_bridge: kennedy-project
custom: ['https://t.me/The_SHIKARI_Network', 'https://t.me/ShikariSupportNetwork']
